#pragma once
#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 416
#define MOVEMENTSPEED 50.0f
#define MARIO_MAP_HEIGHT 13
#define MARIO_MAP_WIDTH 16
#define MARIO_TILE_HEIGHT 32
#define MARIO_TILE_WIDTH 32
#define SHAKE_DURATION 0.25f